In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [3]:
df = pd.read_csv('data/data.csv')

In [4]:
# View the first few records
df.head()

country  year       uniqueid location_type cellphone_access  household_size   
0   Kenya  2018  uniqueid_6056         Urban              Yes               3  \
1   Kenya  2018  uniqueid_6060         Urban              Yes               7   
2   Kenya  2018  uniqueid_6065         Rural               No               3   
3   Kenya  2018  uniqueid_6072         Rural               No               6   
4   Kenya  2018  uniqueid_6073         Urban               No               3   

   age_of_respondent gender_of_respondent relationship_with_head   
0                 30                 Male      Head of Household  \
1                 51                 Male      Head of Household   
2                 77               Female                 Parent   
3                 39               Female      Head of Household   
4                 16                 Male                  Child   

            marital_status                  education_level   
0  Married/Living together              Secondary education  \
1  Married/Living together  Vocational/Specialised training   
2  Married/Living together              No formal education   
3  Married/Living together                Primary education   
4     Single/Never Married              Secondary education   

                       job_type bank_account  
0  Formally employed Government          NaN  
1     Formally employed Private          NaN  
2          Remittance Dependent          NaN  
3          Remittance Dependent          NaN  
4          Remittance Dependent          NaN

In [5]:
# Get information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33610 entries, 0 to 33609
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   country                 33610 non-null  object
 1   year                    33610 non-null  int64 
 2   uniqueid                33610 non-null  object
 3   location_type           33610 non-null  object
 4   cellphone_access        33610 non-null  object
 5   household_size          33610 non-null  int64 
 6   age_of_respondent       33610 non-null  int64 
 7   gender_of_respondent    33610 non-null  object
 8   relationship_with_head  33610 non-null  object
 9   marital_status          33610 non-null  object
 10  education_level         33610 non-null  object
 11  job_type                33610 non-null  object
 12  bank_account            23524 non-null  object
dtypes: int64(3), object(10)
memory usage: 3.3+ MB


In [6]:
# Statistical summary of the dataset
df.describe()

year  household_size  age_of_respondent
count  33610.000000    33610.000000       33610.000000
mean    2016.975930        3.791877          38.656114
std        0.847353        2.223138          16.447127
min     2016.000000        1.000000          16.000000
25%     2016.000000        2.000000          26.000000
50%     2017.000000        3.000000          35.000000
75%     2018.000000        5.000000          49.000000
max     2018.000000       21.000000         100.000000

In [7]:
# checking for spaces in
print(df.columns)

Index(['country', 'year', 'uniqueid', 'location_type', 'cellphone_access',
       'household_size', 'age_of_respondent', 'gender_of_respondent',
       'relationship_with_head', 'marital_status', 'education_level',
       'job_type', 'bank_account'],
      dtype='object')


In [8]:
# Check for missing values
df.isnull().sum()

country                       0
year                          0
uniqueid                      0
location_type                 0
cellphone_access              0
household_size                0
age_of_respondent             0
gender_of_respondent          0
relationship_with_head        0
marital_status                0
education_level               0
job_type                      0
bank_account              10086
dtype: int64

In [9]:
# check for unique values in column bank_account
df['bank_account'].unique()

array([nan, 'Yes', 'No'], dtype=object)

In [10]:
# create a new data frame without the NaN in our target feature
df_wo_target_nan = df.dropna(axis=0)

In [11]:
df_wo_target_nan.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23524 entries, 10086 to 33609
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   country                 23524 non-null  object
 1   year                    23524 non-null  int64 
 2   uniqueid                23524 non-null  object
 3   location_type           23524 non-null  object
 4   cellphone_access        23524 non-null  object
 5   household_size          23524 non-null  int64 
 6   age_of_respondent       23524 non-null  int64 
 7   gender_of_respondent    23524 non-null  object
 8   relationship_with_head  23524 non-null  object
 9   marital_status          23524 non-null  object
 10  education_level         23524 non-null  object
 11  job_type                23524 non-null  object
 12  bank_account            23524 non-null  object
dtypes: int64(3), object(10)
memory usage: 2.5+ MB


In [12]:
df_wo_target_nan.describe()

year  household_size  age_of_respondent
count  23524.000000    23524.000000       23524.000000
mean    2016.975939        3.797483          38.805220
std        0.847371        2.227613          16.520569
min     2016.000000        1.000000          16.000000
25%     2016.000000        2.000000          26.000000
50%     2017.000000        3.000000          35.000000
75%     2018.000000        5.000000          49.000000
max     2018.000000       21.000000         100.000000

In [13]:
df_wo_target_nan.head().T

10086                 10087   
country                                   Kenya                 Kenya  \
year                                       2018                  2018   
uniqueid                             uniqueid_1            uniqueid_2   
location_type                             Rural                 Rural   
cellphone_access                            Yes                    No   
household_size                                3                     5   
age_of_respondent                            24                    70   
gender_of_respondent                     Female                Female   
relationship_with_head                   Spouse     Head of Household   
marital_status          Married/Living together               Widowed   
education_level             Secondary education   No formal education   
job_type                          Self employed  Government Dependent   
bank_account                                Yes                    No   

                                                  10088   
country                                           Kenya  \
year                                               2018   
uniqueid                                     uniqueid_3   
location_type                                     Urban   
cellphone_access                                    Yes   
household_size                                        5   
age_of_respondent                                    26   
gender_of_respondent                               Male   
relationship_with_head                   Other relative   
marital_status                     Single/Never Married   
education_level         Vocational/Specialised training   
job_type                                  Self employed   
bank_account                                        Yes   

                                            10089                 10090  
country                                     Kenya                 Kenya  
year                                         2018                  2018  
uniqueid                               uniqueid_4            uniqueid_5  
location_type                               Rural                 Urban  
cellphone_access                              Yes                    No  
household_size                                  5                     8  
age_of_respondent                              34                    26  
gender_of_respondent                       Female                  Male  
relationship_with_head          Head of Household                 Child  
marital_status            Married/Living together  Single/Never Married  
education_level                 Primary education     Primary education  
job_type                Formally employed Private   Informally employed  
bank_account                                   No                    No

In [14]:
for column in df_wo_target_nan.columns:
    unique_values = df_wo_target_nan[column].unique()
    print(f"Column '{column}' has {len(unique_values)} unique value(s):")
    print(unique_values)
    print()

Column 'country' has 4 unique value(s):
['Kenya' 'Rwanda' 'Tanzania' 'Uganda']

Column 'year' has 3 unique value(s):
[2018 2016 2017]

Column 'uniqueid' has 8735 unique value(s):
['uniqueid_1' 'uniqueid_2' 'uniqueid_3' ... 'uniqueid_8757'
 'uniqueid_8758' 'uniqueid_8759']

Column 'location_type' has 2 unique value(s):
['Rural' 'Urban']

Column 'cellphone_access' has 2 unique value(s):
['Yes' 'No']

Column 'household_size' has 20 unique value(s):
[ 3  5  8  7  1  6  4 10  2 11  9 12 16 15 13 14 21 18 17 20]

Column 'age_of_respondent' has 85 unique value(s):
[ 24  70  26  34  32  42  54  76  40  69  64  31  38  47  27  48  25  21
  18  22  58  55  62  29  35  45  67  19  80  66  50  33  28  51  16  17
  30  37  59  65  46  56  52  23  43  49  44  72  53  63  39  81  78  36
  20  60  95  71  57  85  68  41  61  75  86  73  93  74  88  90  77  84
  82  89  79  83  94  87  92  91  98  97  96  99 100]

Column 'gender_of_respondent' has 2 unique value(s):
['Female' 'Male']

Column 'relations

In [15]:
# Checking for duplicate values
print(f"duplicate values in columns")

display(df_wo_target_nan.duplicated().value_counts())

print("______"*30)

duplicate values in columns


False    23524
Name: count, dtype: int64

____________________________________________________________________________________________________________________________________________________________________________________


In [18]:
# Plotting correlation between numeric columns

import plotly.graph_objects as go

numeric_df = df_wo_target_nan.select_dtypes(include='number')
correlation_matrix = numeric_df.corr()

fig = go.Figure(data=go.Heatmap(z=correlation_matrix.values, x=correlation_matrix.columns, y=correlation_matrix.index))

fig.show()